yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("posts/<int:post_id>/delit/", views.post_delit, name="post_delit"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path(
        "posts/<int:post_id>/delcomment/<int:pk>", views.delite_comment, name="del_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Q, F, CheckConstraint, UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField("Заголовок", max_length=200)
    slug = models.SlugField("Ссылка", unique=True)
    description = models.TextField("Описание")

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField("Загаловок", help_text="Придумай загаловок",
                             max_length=180, blank=True, null=True)
    text = models.TextField("Текст", help_text="Текст поста")
    pub_date = models.DateTimeField("Дата создания", auto_now_add=True)
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        max_length=200,
        blank=True,
        null=True,
        related_name="posts",
        verbose_name="Группа",
        help_text="Добавить пост в группу",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор",
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ("-pub_date",)

    def __str__(self):
        return self.text[:300]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Пост",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор",
    )
    text = models.TextField("Комментарий", help_text="Текст комментария")
    created = models.DateTimeField("Дата создания", auto_now_add=True)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return self.text


class Follow(models.Model):
    author = models.ForeignKey(
        User,
        related_name="following",
        verbose_name="Автор",
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        related_name="follower",
        verbose_name="Подписчик",
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = "Подписку"
        verbose_name_plural = "Подписки"
        constraints = [
            CheckConstraint(check=~Q(author=F('user')),
                            name='author_not_user'),
            UniqueConstraint(fields=['user', 'author'],
                             name='unique_author_unique')
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "text", "group", "image")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post

User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGINATOR_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, settings.PAGINATOR_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        "group": group,
    }
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    author = User.objects.get(username=username)
    posts_user = Post.objects.filter(author_id=author).order_by("-pub_date")
    paginator = Paginator(posts_user, settings.PAGINATOR_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    user = request.user
    if user.is_authenticated:
        following = Follow.objects.filter(author=author, user=user).count()
    else:
        following = False
    context = {
        "page_obj": page_obj,
        "author": author,
        "following": following,
    }
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post=post).all()
    form = CommentForm()
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST, files=request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author_id = request.user.id
            post.save()
            return redirect("posts:profile", username=request.user.username)
        return render(request, "posts/create_post.html", {"form": form})
    form = PostForm()
    return render(request, "posts/create_post.html", {"form": form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect("posts:post_detail", post_id=post_id)

    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author_id = request.user.id
        post.save()
        return redirect("posts:post_detail", post_id=post_id)
    context = {
        "post": post,
        "form": form,
        "is_edit": True,
    }
    return render(request, "posts/create_post.html", context)


@login_required
def post_delit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect("posts:post_detail", post_id=post_id)
    Post.objects.filter(pk=post.pk).delete()
    return redirect("posts:profile", username=post.author.username)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def delite_comment(request, post_id, pk):
    user = request.user
    author = Comment.objects.get(pk=pk)
    if user == author.author:
        author.delete()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    post_list = Post.objects.filter(author__following__user=user)
    paginator = Paginator(post_list, settings.PAGINATOR_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    if len(post_list) == 0:
        following = False
    else:
        following = True
    context = {
        "page_obj": page_obj,
        "following": following,
    }
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(author=author, user=user).delete()
    return redirect("posts:index")

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block header %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %}
          Редактировать запись
        {% else %}
          Новый пост
        {% endif %}
      </div>
      <div class="card-body">
        {% if form.errors %}
          <div class="form-group row my-3 p-3">
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          </div>
        {% endif %}
        {% if is_edit %}
          <form method="post" action="{% url 'posts:post_edit' post.pk %}" enctype="multipart/form-data">
        {% else %}
          <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
        {% endif %}
          {% csrf_token %}
          {# {{ form.as_p }} #}
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small
                     id="{{ field.id_for_label }}-help"
                     class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
            </div>
            {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% load thumbnail %}
  {% load cache %}
  <article>
    <h1>Ваша личная лента {{ user.username }}</h1><br>
    {% include 'includes/switcher.html' %}
      {% if following %}
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: <a href="{% url 'posts:profile' post.author %}">
              {{ post.author.get_full_name }}</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
              <li>
                Группа: <a href="{% url 'posts:group_list' post.group.slug %}">
                  {{ post.group.title }} </a>
              </li>
            {% endif %}
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          {% if post.title %}
            <h4>{{ post.title }}</h4>
          {% endif %}
          {% if post.text|length > 300 %}
            <p>{{ post|linebreaksbr }}...</p>
          {% else %}
            <p>{{ post.text|linebreaksbr }}</p>
          {% endif %}
          <br>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      {% else %}
        <h3>{{ user.username }}, ты еще не на кого не подписался</h3>
      {% endif %}
    {% include 'includes/paginator.html' %}
  </article>

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
  {% load thumbnail %}
  <article>
    <h1>{{ group.title }}</h1>
    <p>{{ group.description  }}</p>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: <a href="{% url 'posts:profile' post.author %}">
          {{ post.author.get_full_name }}</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {% if post.title %}
        <h4>{{ post.title }}</h4>
      {% endif %}
      {% if post.text|length > 300 %}
        <p>{{ post|linebreaksbr }}...</p>
      {% else %}
        <p>{{ post.text|linebreaksbr }}</p>
      {% endif %}
      <br>
      <a class="btn btn-primary" role="button"
           data-bs-toggle="button"
           href="{% url 'posts:post_detail' post.pk %}">Подробнее</a>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </article>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% load thumbnail %}
  {% load cache %}
  <article>
    <h1>Добро пожаловать на Главную страницу!</h1><br>
    {% include 'includes/switcher.html' %}
    {% cache 20 index_page page_obj.number %}
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: <a href="{% url 'posts:profile' post.author %}">
          {{ post.author.get_full_name }}</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li>
            Группа: <a href="{% url 'posts:group_list' post.group.slug %}">
              {{ post.group.title }} </a>
          </li>
        {% endif %}
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {% if post.title %}
        <h4>{{ post.title }}</h4>
      {% endif %}
      {% if post.text|length > 300 %}
        <p>{{ post|linebreaksbr }}...</p>
      {% else %}
        <p>{{ post.text|linebreaksbr }}</p>
      {% endif %}
      <a class="btn btn-primary" role="button"
         data-bs-toggle="button"
         href="{% url 'posts:post_detail' post.pk %}">Подробнее</a>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'includes/paginator.html' %}
  </article>

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block header %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: <br>
          {{ post.pub_date|date:"d E Y" }}
        </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
              </a>
            </li>
          {% endif %}
        <li class="list-group-item">
          Автор: <a href="{% url 'posts:profile' post.author %}">
          {{ post.author.get_full_name }}</a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  {{ post.author.posts.count }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Комментариев:  {{ comments.count }}
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {% if post.title %}
        <h4>{{ post.title }}</h4>
      {% endif %}
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if request.user.is_authenticated %}
        {% if post.author.username == user.username %}
          <a class="btn btn-primary" role="button"
             href="{% url 'posts:post_edit' post.pk %}">
             Редактировать пост</a>
          <a class="btn btn-danger" role="button"
             href="{% url 'posts:post_delit' post.pk %}">
             Удалить пост</a>
        {% endif %}
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                <div class="col-sm-10">
                  {{ form.text|addclass:"form-control" }}
                </div>
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
        {% for comment in comments %}
          {% with text=comment.text username=comment.author.username pk=comment.pk fullname=comment.author.get_full_name %}
            <div class="media mb-4">
              <div class="media-body">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">
                      <a href="{% url 'posts:profile' username %}">
                        @{{ username }} ({{ fullname }})
                      </a>
                    </h5>
                    <p class="card-text">{{ text|linebreaksbr }}</p>
                    {% if username == request.user.username %}
                    <a href="{% url 'posts:del_comment' post.pk pk %}"
                       class="card-link">
                      удалить комментарий
                    </a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          {% endwith %}
        {% endfor %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block header %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
  {% load thumbnail %}
  <h1>Все посты пользователя  {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
    {% if user.username != author.username %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
        Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
    <br>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
        <li>
          Группа: <a href="{% url 'posts:group_list' post.group.slug %}">
            {{ post.group.title }} </a>
        </li>
      {% endif %}
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {% if post.title %}
        <h4>{{ post.title }}</h4>
      {% endif %}
      {% if post.text|length > 300 %}
        <p>{{ post|linebreaksbr }}...</p>
      {% else %}
        <p>{{ post.text|linebreaksbr }}</p>
      {% endif %}
      <a class="btn btn-primary" role="button"
         data-bs-toggle="button"
         href="{% url 'posts:post_detail' post.pk %}">Подробнее</a>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}